model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "."
  monitor: valid/loss
  save_last: True

tune_report_callback:
  _target_: ray.tune.integration.pytorch_lightning.TuneReportCallback
  metrics:
    loss: valid/loss
