model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "."
  monitor: valid/loss_all
  save_last: True

tune_report_callback:
  _target_: ray.tune.integration.pytorch_lightning.TuneReportCallback
  metrics:
    loss: valid/loss_all

raster_plot_callback:
  _target_: ctd.data_modeling.callbacks.SAE.sim_callbacks.RasterPlot
  log_every_n_epochs: 100

trajectory_plot_callback:
  _target_: ctd.data_modeling.callbacks.SAE.sim_callbacks.TrajectoryPlot
  log_every_n_epochs: 100

trajectory_callback:
  _target_: ctd.data_modeling.callbacks.SAE.sim_callbacks.TrajectoryPlotOverTimeCallback
  log_every_n_epochs: 100

avg_firing_rate_callback:
  _target_: ctd.data_modeling.callbacks.SAE.sim_callbacks.AvgFiringRateCallback
  log_every_n_epochs: 100

inputs_plot:
  _target_: ctd.data_modeling.callbacks.SAE.sim_callbacks.InputsPlot
  log_every_n_epochs: 100
